[2022-11-22 20:23:17] [MainThread] [INFO  ] [petstore.py: 16]: STARTED: Setup test operations.
[2022-11-22 20:23:17] [MainThread] [INFO  ] [petstore.py: 20]: ENDED: Setup test suite operations.
[2022-11-22 20:23:17] [MainThread] [INFO  ] [test_users.py: 17]: ENDED: Method Level setup test data.
[2022-11-22 20:23:17] [MainThread] [DEBUG ] [rest_client.py: 54]: Request URL : https://petstore.swagger.io
[2022-11-22 20:23:17] [MainThread] [DEBUG ] [rest_client.py: 55]: Request type : POST
[2022-11-22 20:23:17] [MainThread] [DEBUG ] [rest_client.py: 56]: Request Header : {'Content-type': 'application/json', 'Accept': 'application/json'}
[2022-11-22 20:23:17] [MainThread] [DEBUG ] [rest_client.py: 57]: Request Parameters : None
[2022-11-22 20:23:17] [MainThread] [DEBUG ] [rest_client.py: 58]: json_dict: null
[2022-11-22 20:23:17] [MainThread] [DEBUG ] [rest_client.py: 60]: Data : [{'id': 0, 'username': 'ranjan', 'firstName': 'ranjan', 'lastName': 'naik', 'email': 'test0@abc.com', 'password': 'test@123', 'phone': '123-456789', 'userStatus': 0}]
[2022-11-22 20:23:20] [MainThread] [DEBUG ] [connectionpool.py: 1005]: Starting new HTTPS connection (1): petstore.swagger.io:443
[2022-11-22 20:23:22] [MainThread] [DEBUG ] [connectionpool.py: 465]: https://petstore.swagger.io:443 "POST / HTTP/1.1" 405 150
[2022-11-22 20:23:23] [MainThread] [DEBUG ] [rest_client.py: 67]: Response Object: <Response [405]>
[2022-11-22 20:23:33] [MainThread] [ERROR ] [rest_client.py: 68]: Response Text: <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
Traceback (most recent call last):
  File "C:\Users\755344\codebase\framework_sampler\commons\rest_client.py", line 68, in rest_call
    try:
  File "c:\users\755344\venv37_eostest\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\755344\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\755344\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\755344\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-11-22 20:23:33] [MainThread] [INFO  ] [test_users.py: 23]: STARTED: Teardown of test data
[2022-11-22 20:23:33] [MainThread] [INFO  ] [test_users.py: 24]: ENDED: Method Level Teardown test data.
[2022-11-22 20:23:33] [MainThread] [INFO  ] [petstore.py: 22]: STARTED: Test suite Teardown operations
[2022-11-22 20:23:33] [MainThread] [INFO  ] [petstore.py: 24]: ENDED: Test suite Teardown operations
